name: Snyk SCA, Code, IaC and Container CLI monitor example

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SNYK_API: https://app.eu.snyk.io/api
  IMAGE_NAME: nodejs-goof
  
jobs:
  build:
    name: IAC Net New Issues
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Setup Snyk + snyk-to-html # For information about the required commands for generating an HTML report see https://github.com/snyk/snyk-to-html
        run: |
          npm install snyk snyk-delta -g
          snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Snyk IaC
        run: |
          snyk iac test --json-file-output=snyk-iac-${{ github.ref }}.json \
          --json --print-deps | --print-deps | snyk-delta \
          --baselineOrg ${{ sercets.SNYK_ORG_ID }} --setPassIfNoBaseline true 
