name: Snyk IaC CLI PR check delta

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
  build:
    name: IAC Net New Issues
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Snyk + snyk-to-html # For information about the required commands for generating an HTML report see https://github.com/snyk/snyk-to-html
        run: |
          npm install snyk snyk-delta -g
          snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Snyk IaC
        run: |
          snyk iac test --json-file-output=snyk-iac-${{ github.repository_name }}.json
